jupyterhub:
    hub:
        config:
            OAuthenticator:
                oauth_callback_url: ENC[AES256_GCM,data:0zD93NikHvcHzBjlfSwox2cwcSc3iux4nfsyIsBYUXE/ipGwOwcQN+jd+HeJE9ccHwRhjg==,iv:o7ZBx+o9ztQNIw9VMfKdHz9AiQFfhoDHH26CPqezYbc=,tag:L0NtNzyD9CiQ+pSU07fbGQ==,type:str]
                client_id: ENC[AES256_GCM,data:ZjJr57eGTz/RC0l4o4ZhexUaqDs=,iv:BZZckRXJmLoPgox5GcBJ0devx0e0izSu//3jLgB26ks=,tag:qFYpPQxWn2qcCh8OZynKxA==,type:str]
                client_secret: ENC[AES256_GCM,data:OEcneEHh/RuNgL4IQwacaHEdUpWJ+zt6CVbJkCct0Dqfpdn+ZfRakg==,iv:CWjyZD/D4luX5cok1l7srh6UybO0NqTUvgPqiYL846Q=,tag:wBYwHfE2f9qfowGh2BGJZA==,type:str]
            JupyterHub:
                authenticator_class: ENC[AES256_GCM,data:OOWpNi+6,iv:Z/S+qw3XmxnXioJ8zBlI5Vr+n7XxYkU/zu0rMgqr9CI=,tag:UsYJv0ouK59zfuybZITiOA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2024-12-05T00:10:01Z"
          enc: CiQA471gaj6c+lmwvfanSQK7d5YNyQ6H4NyU155RUa1tu2k1oFYSSQDosIMbhUjljQQ+kkkX+j9TE0wq6tPy8z2w9jqFf5y7rNRl2zmuG9q7rEZDZySF/SfgX0prMgJnsgO/W2WcXbe9JuHth4KHRQg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-28T01:42:23Z"
    mac: ENC[AES256_GCM,data:AxS5XR01L4qdkuowX8b2X0qjaStVy51Xyz5IjIjfEiWbbn9tzXNlO+99P4/Bl5roINDtcYKsyaakhAwY64TKe+XtNyle6AVEOCmzLJH+SH/v7mDoS23IwZvRMSLti7XeJTC7QGRF2Js6GlaFI0wveQP/JbFL1WMTZzF4l2Vaf/s=,iv:lypDsD87VoNHhlwdOpayKHihjZ09ihdyKRr2+k7GR8M=,tag:1ZnHrXoCifRPjry3lAGNhw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
