jupyterhub:
    hub:
        config:
            OAuthenticator:
                oauth_callback_url: ENC[AES256_GCM,data:we5Cu7DSGpXz0ongcG5AQoJweNNfCiFvYaQYoF4x36CHIhIFudVcdos304W/WLvgJaNOYw==,iv:yrhGz49gY5qq8RvA0CfaQWOo0ZNB95E1jvFASefO0og=,tag:RoyP+BALkubV1BSWFl3Nww==,type:str]
                client_id: ENC[AES256_GCM,data:3jJikt9DJDClHkJuYtVTwxVyO0k=,iv:atovn0N4a8ruNyWWBkScCF20+7B1LSnayUECheDvLWw=,tag:SjlvQqr7Qz4XKYzh4atSLg==,type:str]
                client_secret: ENC[AES256_GCM,data:3Q9QrTtBkeDGdtF1klyW3zV/TP4H3ybHPSVTZo2V8O/Qh88gqMLRUw==,iv:BoAPkdxjJzZGWvCLAiy3/1/Ogu7gApPVMe/KIkfEn3o=,tag:2BMUmal6ctX783rzMX0QyA==,type:str]
            JupyterHub:
                authenticator_class: ENC[AES256_GCM,data:b1/HLHON,iv:JzVJqFpsND7pD4trVc96YCX+TL5Tvkp3F4GXCZ/xSTQ=,tag:vdAztpajwPUCHtNhyDanyg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2024-12-05T00:10:26Z"
          enc: CiQA471gahBK84Oz9C0QFLXa7TlxvHmNq21jRXuA7nRFs0R/64ASSQDosIMbrVFvliov/tRMw3UgaCWQIS4p58kawa+mwuAEiliKbsvyn0VijBrJeXglTF//2p+Vn6hF50DkE7ba5blLTfl5rlMPDD0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-28T01:41:39Z"
    mac: ENC[AES256_GCM,data:oSddozok0eNDHTJKHRC9yHyemYZyl8nTCvNLScuggYyrqJSmEStEfMIIQ7Sw+FNVc9IqiHCdCuI0dW8VGBXJXt4gRg5vXJ7tIabOVpSkvwtyxFq2k5VQgvWoMypZWqMey4FyZrJV9JeWk9/h8zjSh6bPpW2F/W3y5WEUszmisVE=,iv:JDSI5+93z3WN/WbIw49oQTwK7JjDYjF+rp+tNk+JCiI=,tag:kRlISf0gB5WnWO3mYfL/yg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
