jupyterhub:
    hub:
        extraContainers:
            - name: ENC[AES256_GCM,data:BncfDb8g7gGYOCAUYE4=,iv:JAACmwtfrH/DeHrQUOek+esaZTIOeQayqIpPR4c90vE=,tag:a7WRFAoV2+y9IeEbSf91rA==,type:str]
              image: ENC[AES256_GCM,data:b1VqaE2LZLb5qA==,iv:uIPXJOyuND/B0neb4DkwfdCF8fCs3HbeI5HuNq1cDYc=,tag:DpmkmZvQcyxB6Gqr9vKNMA==,type:str]
              workingDir: ENC[AES256_GCM,data:f3N+zI+8IfqT,iv:9rP7XbgEidfMKwurTXVIT16Yg5xoJ8BkkBx70qBXSzE=,tag:IzKS87Rq+J9W+z/Kv/uEgg==,type:str]
              command:
                - ENC[AES256_GCM,data:c3If8mkB7w==,iv:925PPELDruTWy1B3ZmtztRrlSd1p1AXRy6eYZ3ufZ1k=,tag:I5jkydGrF+y8Gn69W2arJw==,type:str]
              args:
                - ENC[AES256_GCM,data:tQw=,iv:LKukzLZljZhudhGac4WinoUFekI4RCobz/YHBgK7cOw=,tag:fdbKqDFX72SD8MWfv0Nupw==,type:str]
                - ENC[AES256_GCM,data:GJ05TMinGmasqr0usHL69/vYMeT5nXpSS5edyhGqrM0LcWWFn2fIzs/NPxWT1SRAo63iUjBo3kXUTINw+XqbPl1gu60ITMnd,iv:7B9+Nb5vMK5lYSrdp+FminOGz651OXN/gfIzLTx125k=,tag:Wl1OYGBbGxCR0PlkLxpkng==,type:comment]
                - ENC[AES256_GCM,data:rbR0m//ijenrlw4f0uNZBA/UX9cQjCTCrW3jLOEuEFY3qGQLahd+0KVJXzzx5vGPAGFCsCtYDd3Dz65Bk8/x9EeMQKnBPbmyLrhjFgxvkg==,iv:xcJS7UijOSMX05IAj5f2tUzAaKJx06Sr1gW+UHiTNVM=,tag:wDLWnsX+ADUEoUKqN7P31g==,type:str]
              securityContext:
                runAsUser: ENC[AES256_GCM,data:TNLf8A==,iv:c/urErx6ta6gS3iIMGwzDXdVx8LCdcHK4MXMhMcHgHk=,tag:rPkyXCULc7ri4E14UM68HQ==,type:int]
                allowPrivilegeEscalation: ENC[AES256_GCM,data:8WDkVW0=,iv:pX2qbiGkvDJbFkTt+JDQJYjH81b7Kh8aOQxIaWKOnaQ=,tag:2GKYdA/ztQiYTSnYkGzmqA==,type:bool]
                readOnlyRootFilesystem: ENC[AES256_GCM,data:SHH2Lg==,iv:mSbuGRGlB2FauDVt5c6wQOyzyIpfaaHkBwhmHrSh8t0=,tag:GP0CFuHkt2OMVMgtWnfnEA==,type:bool]
              volumeMounts:
                - name: ENC[AES256_GCM,data:JrpSysBVCz0vzXiQ6TO3NA==,iv:pX+KRDG3EXtnKzk6BS40uDBWWuMzunAGv1ph8dX4tXg=,tag:AySajV+DKfmTQvfW1vIwpA==,type:str]
                  mountPath: ENC[AES256_GCM,data:qjcM/z3Sw9mr,iv:kSN1ueL4MHzsRjWq0oaMrr0ZjwUgRKcIRv7fRSmxWqM=,tag:ea4l042Vp3qCg5bjU9WNZQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2024-12-05T00:10:26Z"
          enc: CiQA471gahBK84Oz9C0QFLXa7TlxvHmNq21jRXuA7nRFs0R/64ASSQDosIMbrVFvliov/tRMw3UgaCWQIS4p58kawa+mwuAEiliKbsvyn0VijBrJeXglTF//2p+Vn6hF50DkE7ba5blLTfl5rlMPDD0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-05T00:11:41Z"
    mac: ENC[AES256_GCM,data:TcuoiYhC9t1KoxI6LkZESDi+V4zMb6U7aUtnEMX1UEcFjvpCsRey0/7MUZ7dgok/Iby0AoMWg5X1JhQ7+gFKjO2ugj9CDVSbPX9+YmnJ1Ossrp6Xii7RHSz1a+WsfB6Y0inK4oXFwoPPEcv4ifCX3R5qqeNpGIK1HskhJPrjXbA=,iv:a7pNfe55XZd+EhqWWQ8l5ELRg1/5hGxYYqqMJOPkZNE=,tag:pr2jSS00DC7PH0s8hqgdGg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
