creation_rules:
  - path_regex: deployments/.*/secrets/.*
    kms: arn:aws:kms:us-west-2:296062562246:alias/sops
  - path_regex: support/secrets.yaml
    kms: arn:aws:kms:us-west-2:296062562246:alias/sops
