jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:EaTGrg==,iv:gz8xemgkLGcxUlBcHaUQGULYSe6EzvsF+ogMGTKeSTs=,tag:JsNLMsGhZMBlySGLMgGplQ==,type:str]
                client_secret: ENC[AES256_GCM,data:AiXK2cRsHg4=,iv:CV1ndq3oClHsdQhlCFnwa9pwEJ5cssHj5XYaPzH7yzs=,tag:UB6bcbl8mC0mfz/FucfaGg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-22T20:42:15Z"
          enc: CiQA471gav0SSk9smMEZ2YQ53RrMzQdsbuNeHmlKpOwwsakl6KASSQA0woZQkbdBIL14VpumUTSgCYetOI+ilRNfIAXr2OO55gp4s4UzuK0ceYORsK7jaXEAi60SUwjC8srnBbHtFu/5nqZEV0z4QLA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-22T20:42:16Z"
    mac: ENC[AES256_GCM,data:dngp319WDUObpUyfUw3Nhpxr7wZDX2XucscNLMs9dcS0WPt+YLWIKZCV1QXFqM2wQzB8+XEA4xwuGGEQDRQZ54S5CoJ3mjV4t5tYNfQ+KlQ8vyE5AdDHzk/L0wHTz0xJc78GblisiI507G20osKBFTmrlpqvlsZL9FD9+BSBNPE=,iv:5PhJmW3gk4y40ggbbRf25K5Gmp+BjOR3eUxhpzd3HHY=,tag:HyyEQoiN6XgZ9IGqmve9ZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
