jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Ua+oJA==,iv:e9HAxJ9RajEEloX+G8wmoW7wIvU6r+5wgDoV3bl/Txo=,tag:o7cWW8ePX0EMnkeqsIny9w==,type:str]
                client_secret: ENC[AES256_GCM,data:1e60uTSUrn0=,iv:WzmI9TfRmsAWQIfSCxncshrQ0ux3qv8bjL/KHDpz+0U=,tag:ZtMzUC1PHCFEhYFwjfiUlg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-23T00:35:33Z"
          enc: CiQA471gas5ToZKjlKJpIZhNMGmgAA7juWYMKMRZ/wtwBmy9NXwSSQA0woZQJY9YJhyFmdMJx7ESFkxfdcLEgRLzeGFw5dB5nDI7OCHgNAsBMN9A749HWRfMzK1uXwov481xY1rt2MBI9MhDdJ3WQ2c=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-23T00:35:34Z"
    mac: ENC[AES256_GCM,data:AkLWlH9UiktYwhxjN4Zmj3oIeqgzJKesJOzxp8YnHzc6/YQ77zyBsQnQh7gv6zPucrn1CqfZfOBjujXeNt6tUHhRB1kqwYAo9UUOzmn1r2qP2DphPHphJmVITmZ769A7tn9T9P/F0RgJQAa+Te2bBpwFiyswOrwSP9yyOKC04/0=,iv:b/5nbDqBeTfSkbkbW7baSkTrnhvoM3JMBee08JPPc0E=,tag:x64ViGLWaKVe7lodn9XYDA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
