jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:JOrEGA==,iv:BSFoItkv3aIgUwVkMnz34k290J600x5cs3nxBKZMnIM=,tag:OvmneJdtNMtQG8jD8wgG1w==,type:str]
                client_secret: ENC[AES256_GCM,data:CwDP3wkR7Bw=,iv:bFPiEM257/5gjGQ2EZ2ogq4WdufXt87kvezpz+ypBtw=,tag:sZ22vmpMrHUzcDwSjAHsAw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-23T20:07:10Z"
          enc: CiQA471gaqYQ6SihLrLL4wK9R9eJrXZU0Sz6/qLPdjUESrnZMpESSQA0woZQPnM7oSyKV4sfx3DDTe6DNtJFSSqjFAi+a1fXyXLyWIXyFWYNcd/uTaAu7QKoNB/H/DfBOcNALfCHpq35Q5bY5Uss5I8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-23T20:07:10Z"
    mac: ENC[AES256_GCM,data:d71xazuIJsygGUmwweBVHayLefiKzKExovZP3CWZbL3PTOyEyGKeZAm9Pc57NxoqUfpUK84jQ8m4wm51hSHsIxhGKQyIcE7wkH9ILcHJGiknrrz6T9F3GC0YGYKkm1QBgMG/6cil7EB+2IDLC4RFplWxnWICPc0ZI5xFvLPgCPM=,iv:qggkADj2X67oIAx/5qZnxlBe0Q+i58UMF+aGAayjxto=,tag:wl68k4iJA1FOKl9uyZs2wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
