jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:A+NgXA==,iv:egEAJY4qZzFNfbFFGhZ2RlSHq8w71SI4eszKECYwjPE=,tag:5PlvkJ7+ZuMPpPEvTkfl4w==,type:int]
                client_secret: ENC[AES256_GCM,data:XReiYhdiFyw=,iv:9qjgx6MBKBvfj19n5pHpelKyuJU+jkAZwNFpoN2AyLA=,tag:FRGXEDVEVLRuPjgueKpJlw==,type:int]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-23T20:52:46Z"
          enc: CiQA471gameUIILBmyRIDVsv/NSN6BZ06l/O5u9ilZtIgqAarqESSAA0woZQoidHYTZZn+m+9x8YQOyHEwtPa2vpnNcNifRvpa58k/8T9ShWgXkd1qjBeSom9iDM11fEvkPBaF0edNT31K8ur0iqRw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-23T20:52:46Z"
    mac: ENC[AES256_GCM,data:dkbTVKZkMPDMA9tjwqOBsHPi0yKZwD1/WdIWJ41xxuHgLKZemKwcwbl32BakZtax4gIM09SbAZ7w6WBKk17ssTsAZ3RTAgDG28IlMy/Mjp9XGSb/7bZaadu3zxkaDCGWfY1iLu+hSiRR9t66MaWdRgDquNhvHNDsMN5fsoNMhO8=,iv:U+C/AMZaPLxQNcgTjuK0gujSqZLfewFHqXdeXgzGG3A=,tag:Z4CMUfy/QQNmv2D/GaQdJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
