jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:L9rrxQ==,iv:cKaEAxzweEXi61zl/aWuiQIaNiHCCPRzldytMW7lmgE=,tag:EllnbQpVcgtr//JLimQpTg==,type:int]
                client_secret: ENC[AES256_GCM,data:x6+6FDKAjwY=,iv:sV2lKoRc0jDWZX6HnUGUZZhxo37GGCmje7MIGUILZ8g=,tag:onRm6joDu49Drv45lsqOFA==,type:int]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-22T20:42:16Z"
          enc: CiQA471gav4YBHKV/z0LbICH7zALQDCoz9MiU2rgbCVoCpfbauUSSQA0woZQb0sOZWFlokJvya8fpS3dv4kzntVnEmVQ405BpCsnfHTtjnfJe2YkYsC0r/jMR71EIk1I0EAtRgPx/hUJAxK4uSe32UM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-22T20:42:17Z"
    mac: ENC[AES256_GCM,data:pzfXihIDvVtpuuhYFfZdUaNjgDRu+J+wMaQ1vz1R0H8nL9+3moc6X2K8EUYmdL+dbgJV7OnsnZOHqDWnVHHbY4DgZvseFXxkfMlC5VuaStQj6Z0wx6Hvh1x55QQ02xrIcCYx27EkujdQLppLxFxQuw8JXvM77oO7wAaWj39hhMA=,iv:HPLPtla8UOLF4s1yv8WsIBrb7w0n5bWfqPO5y4e8diM=,tag:aMDPjo3GTlrvg++xga/GNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
