jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:3mc6Fw==,iv:Hb3kUhD4kGicn5KkfmtFC8PX6N8OPcQv6QoiyDZN5As=,tag:vVIFOIVDR1vZY8PSRh43nQ==,type:int]
                client_secret: ENC[AES256_GCM,data:VoxHz7tSJoU=,iv:tHN6eGwmbkM8S8GP+bfWJut3c5t22DNPR1ueeFRX6+w=,tag:r5C0VSx3JCTvf/lmwv+HQw==,type:int]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-22T21:00:59Z"
          enc: CiQA471gan0dM+biycyjzOsRyagKBgwBjxRJ6sOFNAo9pEGaW8oSSAA0woZQC0mGxFkMLt90gJWktp3rsdohMyKPVmUWLz60XjgQb8ha6bHr60r7x3aeCbbHvV5AClNLzrPbTqGhlH0I9bQMz+6oUQ==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-22T21:01:01Z"
    mac: ENC[AES256_GCM,data:sEaC4lYmVBCCZiUCixigAOVFRA2KdJYDgxbzOg6F9zJsVV9NQR5Kcyydam/CjPLM62bMZHBd+9zsAOoGnmqxcvqreMyQrjnxQFRmYYn+iHzMb5zT4LVA4xQvNdUXuKhsPFZfSKpTeLJ8IzSCj/iQrCpG8b3M+Ys+tAK328iXNFI=,iv:VG7uyDZppalTXZr2QgXcvb2cAXnl4XDlw9MhkS2l96g=,tag:R2coHxsdO9ITGXUYIr1uog==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
