nfsPVC:
  nfs:
    shareName: shares/newschool/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - newschool.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - newschool.jupyter.cal-icor.org
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
    config:
        CILogonOAuthenticator:
          oauth_callback_url: https://newschool.jupyter.cal-icor.org/hub/oauth_callback
