jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:UE0eN9gko2LK2TCCCq9kKbE=,iv:itsLQHKcZpruLtrNvBiiLGvo5Yi3g/dkUjx82dvW/6c=,tag:JO7qhKFcya4yh87yMfK6CA==,type:str]
                client_secret: ENC[AES256_GCM,data:ijR1pg5mHlTHJE8+mhGuLw3QfcU28J3oVU5kdb13soEgJVwZ1dEYXsU0N4CPFtkJ/PPRudOaBdL+FS45H7Kldg==,iv:ZqRDVcwhKyaptEr8uDCEBBfwKzf3oLUSgPfRdtMXJC0=,tag:PG+cfN/sQ/yPT+XPsfpg7g==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:JxkrNlR/xVmS7cPmdy3tNOZQQSIJxkuQouEcXJq9ZqR4W8McAp/wUzbTpzA4T52s1iK8Ja3mznZlZdY4F4D9oYBedTanF+yJig==,iv:DJZJT8T8sxDgLftJRLa3wdSslWMBu/LXkWgVvncZJCY=,tag:dQUhemzFmzvDbqLzngIyKw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2024-11-07T21:08:07Z"
          enc: CiQA471gail/PfEPwxUF4maqcNqakNA/egOGdIVHIc8zEhToNtMSSQDosIMbQNQI0YEuZa6WfpMm7Qpo6CJthv0zuA7bv+we9zmDLuN1G6uKjhswM67EtZvDJUJ3CJGQFKCvMv9AvOXP5UQO31PRlW8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-08T00:18:54Z"
    mac: ENC[AES256_GCM,data:MQssGcJNYGG2Ry/f/M84QJYkLP4Pb6BMSG/rZ/acIFyYSOMqQPzx97YxDuiSsn/CSLDuCSgosnQBGhhEsOi4WFboUEUIayFdqtZX0iJ3fjPVDMcsOX7+gBvdSMTLZkbzFcJhkAG88ShOoZOKkjtXdAEbyOMhL8gg/lMxBtAkitE=,iv:qnDfokCIxi9DzI2HISjSNbCEs+7BjRf0iIknB9iRd7E=,tag:6jxFN6nnWFeh8gaIZZVALg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
