jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:n9QBDpofRdPxOJgs/cahoEs=,iv:Zhf3PuxOpz8eaEDN4RQP8Xy+u6K5AQEK6r1ImePn8e8=,tag:QQH2ntBb95TVu6K0qIcZAA==,type:str]
                client_secret: ENC[AES256_GCM,data:RB4JtMmR/Kt9wbF5MRU0PU5W7zXb8kLmrhoktMv0VMa68qEA/WRMszzUzKwx2u6w+OVC1oheYCkSvLsGboXjXA==,iv:mDI0ZvmA9ID7w6GZHrLIiEIf3ZJ/cxNJz4T5D9/9LiE=,tag:52bUXDI59MU1xBdf5XXBrQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:yGnS7nlryKW8zIAG+RNsOg6+fLYJC+EmyXM7AzMjo49L6ZUoR0l+jdbXGeItkHc3N+rwpgE3GIW6/SV3HQ5YoN6Q4rwlh8xFRA==,iv:Wbvp2m04vbMtKNBjNzLkFvZSGhMFVZ6sbg5Qggh31CI=,tag:jSpMOdjFObaHTylOlOajxQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2024-11-08T00:17:00Z"
          enc: CiQA471gajcQFd6Z4z0BfjTbg0LhAK3BS71xLvoQtkalkts8gxsSSQDosIMbC21Fnp1Svwk7AfhofovGARSxklFyG3PaohyjmtDa2EAmJ+ypMNDv6625s6zXAbmuHgsT64Jd5G/6ujPADHXdoBXnxio=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-08T00:19:15Z"
    mac: ENC[AES256_GCM,data:qHj1yo8YiWbkBOEEAGsLUfDhXPJSFJWYbInzKt0bPU42W0rZQgSh9Xr9L7oToSfBB79vdvJwH9G/pUJA8lH0zxMONMtYXm7knpzkvRbRua+f5eS5KXLy3JZJVRnI+ZarUrk/jVZ70oaVZwnHpu1zcRC8Vu5m1i56n6T6IHorQZ4=,iv:9iWjgk6cfJYfw9ZXgfRHf1uFCmQC1EHlJ0JLhFMPCw0=,tag:tCXg9mDVdtktnKoxHr3Iyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
